let actionFigures = [
    { name: 'Zoro Price: ₱5,900', description: 'A **Roronoa Zoro** action figure, inspired by *One Piece*, featuring incredible detail and dynamic poseability. This collectible showcases Zoro’s signature green haramaki, three-sword style (Santoryu), and intense battle expression. The figure comes with interchangeable swords, including Wado Ichimonji, Sandai Kitetsu, and Enma, along with multiple hand and face options for customizable display. With expert craftsmanship, vibrant colors, and dynamic articulation, this Zoro figure is perfect for anime fans and collectors looking to bring the legendary swordsman to life!', image: 'img/b1.webp' },
    { name: 'Luffy Price: ₱7,900', description: 'A Monkey D. Luffy action figure, inspired by One Piece, capturing the energy and determination of the future Pirate King! This highly detailed collectible features Luffy in his iconic straw hat, red vest, blue shorts, and sandals, with a dynamic pose showcasing his adventurous spirit. The figure includes interchangeable hands, expressive faceplates, and signature effects like stretching rubber arms for his Gomu Gomu no Mi attacks. With vibrant colors, expert sculpting, and dynamic articulation, this Luffy figure is a must-have for fans looking to bring the Straw Hat Captain to life!', image: 'img/b2.webp' },
    { name: 'Nami Price: ₱3,900', description: 'A **Nami** action figure, inspired by *One Piece*, perfectly capturing the beauty, intelligence, and adventurous spirit of the Straw Hat crew’s navigator! This highly detailed collectible features Nami in her signature outfit, complete with her signature orange hair and confident expression. The figure includes interchangeable faceplates, hands, and her **Clima-Tact** staff for recreating iconic battle scenes. With vibrant colors, expert sculpting, and dynamic articulation, this Nami figure is a must-have for fans who want to bring the beloved navigator to life in their collection!', image: 'img/n3.webp' },
    { name: 'Yamato Price: ₱8,900', description: 'A **Yamato** action figure, inspired by *One Piece*, capturing the powerful presence and warrior spirit of Kaido’s self-proclaimed son! This highly detailed collectible features Yamato in his signature **Oni-inspired** attire, complete with flowing white hair, red horns, and a fierce expression. The figure includes interchangeable faceplates, hands, and **Takeru**, his massive kanabo club, allowing for dynamic battle poses. With stunning sculpting, vibrant colors, and excellent articulation, this Yamato figure is perfect for fans looking to bring the legendary fighter to life in their collection!', image: 'img/n4.webp' },
    { name: 'Robin Price: ₱6,900', description: 'A **Nico Robin** action figure, inspired by *One Piece*, beautifully capturing the elegance, intelligence, and strength of the Straw Hat crew’s archaeologist! This highly detailed collectible features Robin in her signature outfit, complete with her stylish sunglasses, long black hair, and calm, confident expression. The figure includes interchangeable faceplates, hands, and **Hana Hana no Mi** effect parts to recreate her iconic Devil Fruit abilities. With expert sculpting, vibrant colors, and dynamic articulation, this Robin figure is a must-have for fans looking to add the "Devil Child" to their collection!', image: 'img/n5.webp' },
    { name: 'Law Price: ₱8,900', description: 'A **Trafalgar D. Water Law** action figure, inspired by *One Piece*, perfectly capturing the cool and calculated demeanor of the Surgeon of Death! This highly detailed collectible features Law in his signature long black coat with the **Heart Pirates** emblem, iconic spotted hat, and fierce expression. The figure includes interchangeable faceplates, hands, and his legendary **Kikoku** sword for dynamic battle poses. With expert sculpting, vibrant colors, and excellent articulation, this Law figure is a must-have for fans looking to bring the mastermind of the Worst Generation to life in their collection!', image: 'img/v6.webp' }
];

let manga = [
    { name: 'OnePiece Vol 1: ₱900', description: 'One Piece Volume 1: Romance Dawn is the exciting beginning of Eiichiro Oda’s legendary manga series! This volume introduces Monkey D. Luffy, a cheerful and determined young pirate who dreams of becoming the King of the Pirates. After accidentally eating the Gomu Gomu no Mi, a Devil Fruit that gives his body rubber-like abilities, Luffy sets out on his grand adventure.', image: 'img/m1.webp' },
    { name: 'OnePiece Vol 2: ₱599', description: 'One Piece Volume 2: Buggy the Clown continues Monkey D. Luffy’s exciting journey to become the King of the Pirates! After recruiting the fearsome swordsman Roronoa Zoro, Luffy sets sail in search of a crew and a ship.', image: 'img/m2.webp' },
    { name: 'OnePiece Vol 10: ₱590', description: 'One Piece Volume 10: OK, Let’s Stand Up! brings the intense conclusion of the Loguetown Arc and the beginning of the epic Baroque Works Saga!', image: 'img/m3.webp' },
    { name: 'OnePiece Vol 7: ₱799', description: 'One Piece Volume 7: The Crap-Geezer continues the Straw Hat Pirates’ intense battle in the Baratie Arc, as Luffy fights to save the floating restaurant and recruit its skilled yet stubborn cook, Sanji!', image: 'img/m4.webp' },
    { name: 'OnePiece Vol 8: ₱899', description: 'One Piece Volume 8: I Wont Die marks the thrilling conclusion of the Baratie Arc and the beginning of the Arlong Park Arc, where Luffy and his crew face their toughest challenge yet!', image: 'img/m5.webp' },
    { name: 'OnePiece Vol 6: ₱999', description: 'One Piece Volume 6: The Oath continues the high-stakes Baratie Arc, where Luffy and his crew face off against the deadly pirate fleet commander, Don Krieg!', image: 'img/m6.webp' }
];

let cards = [
    { name: 'Kid TCG: ₱10,999', description: 'Unleash the power of the future Pirate King with this official Monkey D. Luffy TCG card! Featuring stunning artwork and powerful abilities, this card is a must-have for collectors and competitive players alike.', image: 'img/c1.webp' },
    { name: 'Luffy TCG: ₱5,999', description: 'Command the battlefield with Eustass Kid, the fearsome captain of the Kid Pirates! Known for his raw strength and magnetic abilities, this card is a powerhouse in any deck.', image: 'img/c2.webp' },
    { name: 'Chooper TCG: ₱7,999', description: 'The Straw Hat Pirates’ lovable doctor, Tony Tony Chopper, is here to protect your crew! Small but mighty, Chopper is a vital support card for any deck.', image: 'img/c3.webp' },
    { name: 'Nami TCG: ₱9,999', description: 'Chart your path to victory with Nami, the brilliant navigator of the Straw Hat Pirates! This card is essential for strategic players who love to control the flow of the game.', image: 'img/c4.webp' },
    { name: 'Buggy TCG: ₱8,999', description: 'The infamous Buggy the Clown is here to cause chaos on the battlefield! With his tricky Devil Fruit powers and unpredictable antics, he’s a wild card in any deck.', image: 'img/c5.webp' },
    { name: 'Onima TCG: ₱3,999', description: 'The kunoichi of Wano, Onami, strikes with speed and precision! With her nimble movements and strategic mind, she’s a key asset in any deck.', image: 'img/c6.webp' }
];